= Introduction to PDSL for Java Developers

Software testers typically have small teams that maintain massive projects. Even worse, the test surface of a typical application grows exponentially with the addition of a single feature. The application is often duplicated across multiple platforms requiring _n^2^_ coverage to be executed multiple times. Finally the permutations in the test data typically grow in factorial time (which is almost as bad as it can possibly get).

The Polymorphic DSL pattern solves some of these issues. If combined with techniques like _pairwise testing_ your small team can adequately test these massive applications. 

== Architecture Overview

A general model for PDSL is as follows:

.Polymorphic DSL Basic Model
[cols="1,1,1,1,1"]
|===
Tier | Development Tool Example | Testing Example | Testing Tool Example | Artistic Example 
Domain Specific Language | JVM Bytecode or Language (Java, Kotlin, etc)  | Gherkin Standard |  12 Tone Scale 
Specification Language   | .class File| .feature file | Java, Python, or other  | Code file | Vivaldi's _L'estro armonico_ 
Interface Definition Language | Java Virtual Machine Specification | ANTLR4 | Webdriver API | Sheet Music 
Implementation                        | OpenJDK, OracleJDK, JREs, etc   | Java, Python, Golang, TypeScript, etc | Java, Python, Golang, TypeScript, etc | _Concerto for 4 Violins in D minor_ by Antonio Vivaldi, also separate Harpsichord, Organ and other transcriptions by J.S Bach 
|===


== Domain Specific Language

The Domain Specific Language (DSL) is the protocol or language used to create artifacts that tell an arbitrary implementer _what_ to do. In the PDSL pattern there is a preference for using DSLs in a declarative way because it provides flexibility for the implementors, but the DSL can still be used imperatively if needed.

=== Testing Example

_Gherkin_ is a protocol that was developed for the Cucumber framework. While initially created for the purposes of _Business Driven Developoment_, it is often excellent to use as a DSL. Gherkin is not only a powerful way of defining test cases, but it is language agnostic. This allows tests created in Gherkin to have multiple implementations for different platforms regardless of the different language needs of each platform.

== Specification Language

The Specification Language (at least in the context of the _PDSL_ pattern) is an artifact produced by the DSL. These are often some sort of text or binary file, but as long as it is something that can be created by the DSL that explains how to do something it will be suitable for specifications.

=== Testing Example

The .feature files created by Gherkin:
[source,cucumber]
----
Feature: Some Application

  Scenario: Some Requirement
    Given the expression "1 + 1"
    When the expression is evaluated
    Then the result is "2"
----

Feature files make it easy to scale requirements across different applications or domains because they are language agnostic.

== Interface Definition Language

The purpose of the Interface Definition Language (IDL) is to provide a bridge between our specifications and the (possibly many) clients that will executing it. While our specifications are technically already language agnostic, typically there may be a complex enough need to *interpret* the specifications that it warrants it's own tier of architecture. That is to say we need a method of taking the highly abstract DSL and begin transforming it into something concrete that a client can understand.

The IDL may also be used for *handling* the specification or *coordinating* or *transforming* information from the abstract specification into more concrete data that will be needed by lower level implementations.

Ideally the Interface Definition is 100% abstract or as abstract as possible. It should also typically language agnostic. Some use cases may have an IDL that is tightly coupled to a specific programming language or platform, but this should be avoided when possible to allow scaling to other platforms if needed.

=== Testing Example

In traditional Cucumber Step Definition files are used as "glue code" to bind sentences to method execution. However a method to make Cucumber code follow PDSL might be to use something like ANTLR4. ANTLR4 is a parser generator, but for that reason it can be used to bind a sentence to a method call _but in a language agnostic way_. ANTLR4 allows you to use code generation to create interfaces in a variety of programming languages (including Swift and Java, which is probably important if you are developing native mobile apps).

What prevents most standard Cucumber projects from following the PDSL pattern is they provide platform specific code in the step definitions. If these are instead replaced with fully abstract interfaces the tests can instead scale to multiple platforms or even tiers of the testing pyramid.

Here is an example of using step definitions poorly (it cannot scale out)

[source,java]
----
public class SomeStepDefinition {

	// Oh no! This step definition will only be usable for web tests! We'll need to rewrite all of
	// this again for the android application!
	private WebDriver webDriver;

	@Given("the customer selects a product in the store")
	public void givenTheExpression(int x, int y) {
		webDriver.get("some-store.com");
		webDriver.findElement(By.id("some-product")).click();		
	}
}
----

Here the problem is fixed by creating an Interface Definition Language with simple interfaces

[source,java]
----

public interface BuyProducts {
	void selectProduct();
}

public class SomeStepDefinition {

	// Initialize with dependency injection
	private BuyProducts buyProducts;

	@Given("the customer selects a product in the store")
	public void givenTheExpression(int x, int y) {
		// The interface can have a web, android or iOS implementation.
		// They can use the libraries or frameworks that make sense for them
		buyProducts.selectProduct();
	}
}
----

The mere act of using interfaces means that a feature change won't require rewriting _n_ different frameworks. In a best case we just need to update the code in a single location. However we might need another step definition file written in Swift to be compatible for an iOS codebase. But If ANTLR4 was used to create the IDL instead it's even better: we can keep _all_ different codebases in sync by generating the interface code from an ANTLR grammar!

With the use of Appium and Webdriver you can technically avoid the need to cross across the language barrier by testing all the platforms. Because Appium implements the WebDriver API you could technically write the same test for all platforms in the same language. This means that you could use an collection of interfaces in a single language and have that be your IDL.

However still might be better off making your IDL language agnostic using some form of code generation instead. It can be surprising how often a project needs to be ported to another language for reasons outside your control.

== Client

The Clients are actual concrete implementations that interact with the Interface Definition Language. At this point they code can  be idiomatic and safely coupled to a specific language or platform. Since the clients follow a common API or contract but vary enough to be useful within different contexts we can say that they are _polymorphic_ at this point.

==== Testing Example

Providing specific implementations for the IDL we can make sure we can change a test and yet still expect multiple test frameworks to notice the change and be in sync!

First an interface is generated by or written from the IDL:
[source,java]
----
public interface BuyProducts {
	void selectProduct();
}
----

Then one implementation can be produced:

[source,java]
----

public class WebBuyProducts implements BuyProducts {
	
	// Uses WebDriver API. 
	private WebDriver webDriver;

	// Constructors ommitted

	public void selectProduct() {
		webDriver.get("some-store.com");
		webDriver.findElement(By.id("some-product")).click();		
	}
}

----

And then another:

[source,java]
----

public class AndroidBuyProducts implements BuyProducts {

	// Using the Espresso testing framework

	public void selectProduct() {
		onView(withId(R.id.product_view),withText("Some Product"))
		.perform(click())
		.check(matches(withText("Product added to cart!")))
	}
}

----

Either implementation can be injected into the IDL. Now the tests have been scaled across platforms!

[source,java]
----
public class SomeStepDefinition {

	// The AndroidBuyProducts or WebBuyProducts can be added to this IDL and a single
	// test will run on both platforms.
	public SomeStepDefinition(BuyProducts buyProducts) {
		this.buyProducts = buyProducts;
	}

	// Initialize with dependency injection
	private BuyProducts buyProducts;

	@Given("the customer selects a product in the store")
	public void givenTheExpression(int x, int y) {
		// The interface can have a web, android and iOS implementation.
		// They can use the libraries or frameworks that make sense for them
		buyProducts.selectProduct();
	}
}
----

